# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a53c9452ed1e602916698d499c0f7c1de6fb315535c9118d8d85502e1d44b1942dcfccebc50314a1b9f3ee36b80b0bcb5894f56c7b2143473f4756b519b362eb
  name: <%= ENV["NAME"] %>
  admin: <%= ENV["ADMIN"] %>
  app_id: <%= ENV["APP_ID"] %>
  app_secret: <%= ENV["APP_SECRET"] %>
  app_token: <%= ENV["APP_TOKEN"] %>
  app_redirect_url: <%= ENV["APP_REDIRECT_URL"] %>
  totp_token: <%= ENV["TOTP_TOKEN"] %>
  mqtt_server: <%= ENV["MQTT_SERVER"] %>
  mqtt_topic: <%= ENV["MQTT_TOPIC"] %>

test:
  secret_key_base: d1023ececc6c8dcf22fdf3cdacd093db73bc1d80e0efd9f54b84c9a68b975ef05b3ed832b334f75b4376dc4740bcc33bc81aa93ceaf9ccdc347991ea16208526

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  name: <%= ENV["NAME"] %>
  admin: <%= ENV["ADMIN"] %>
  git_url: <%= ENV["GIT_URL"] %>
  server_address: <%= ENV["SERVER_ADDRESS"] %>
  server_user: <%= ENV["SERVER_USER"] %>
  app_id: <%= ENV["APP_ID"] %>
  app_secret: <%= ENV["APP_SECRET"] %>
  app_token: <%= ENV["APP_TOKEN"] %>
  app_redirect_url: <%= ENV["APP_REDIRECT_URL"] %>
  totp_token: <%= ENV["TOTP_TOKEN"] %>
  mqtt_server: <%= ENV["MQTT_SERVER"] %>
  mqtt_topic: <%= ENV["MQTT_TOPIC"] %>

  # Rails.application.secrets.app_id